#!/usr/bin/env bash

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "VPN name:"
read NAME

if [ -d "/vpn/$NAME" ]; then
    docker volume rm "vpn_$NAME"
    bash /vpn/${NAME}/stop
    rm -rf /vpn/${NAME}
else
    echo "No such VPN."
    exit;
fi
