#!/usr/bin/env bash

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIRNAME}/../.config/vars.sh

CLIENT_NAME=$1

if [ "$CLIENT_NAME" = "" ]; then
    echo "Client name:"
    read CLIENT_NAME
fi

echo "No pass (yes/no; default: no):"
read NO_PASS

if [ "$NO_PASS" = "yes" ]; then
    NO_PASS="nopass"
else
    NO_PASS=""
fi

docker run -v vpn_${NAME}:/etc/openvpn --rm -it newtoncodes/vpn-openvpn-dnsmasq easyrsa build-client-full ${CLIENT_NAME} ${NO_PASS}

echo ""
echo ""

docker run -v vpn_${NAME}:/etc/openvpn --rm newtoncodes/vpn-openvpn-dnsmasq ovpn_getclient ${CLIENT_NAME}
