#!/usr/bin/env bash

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIRNAME}/../.config/vars.sh

CLIENT_NAME=$1

if [ "$CLIENT_NAME" = "" ]; then
    echo "Client name:"
    read CLIENT_NAME
fi

docker run -v vpn_${NAME}:/etc/openvpn --rm newtoncodes/vpn-openvpn-dnsmasq ovpn_getclient ${CLIENT_NAME}
