#!/usr/bin/env bash

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIRNAME}/../.config/vars.sh

docker run --rm -it -v vpn_${NAME}:/etc/openvpn newtoncodes/vpn-openvpn-dnsmasq ovpn_listclients
