version: '3'

volumes:
  vpn_{{NAME}}:
    external: true

services:
  vpn_{{NAME}}:
    image: newtoncodes/vpn-openvpn-dnsmasq
    container_name: vpn_{{NAME}}
    cap_add:
     - NET_ADMIN
    ports:
     - "{{PORT}}:1194/{{PROTOCOL}}"
    restart: always
    privileged: true
    volumes:
     - vpn_{{NAME}}:/data
