#!/usr/bin/env bash

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIRNAME}/.config/vars.sh

nano /var/lib/docker/volumes/vpn_${NAME}/_data/openvpn.conf

echo "Restart (yes/no; default: no):"
read RESTART

if [ "$RESTART" = "yes" ]; then
    source ${DIRNAME}/restart
fi